name: Python CI

# Triger the workflow on any push to th main branch or pull request
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            # step 1: check out the code from repo
            - name: Check out code
              uses: actions/checkout@v2

            # step 2: set up pyhton env
            - name: Set up python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'

            # step 3: Install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            # step 4: Run tests
            - name: Run tests
              run: pytest
